#! /bin/sh
#
# portmap       Start/Stop RPC portmapper
#
# chkconfig: 345 13 87
# description: The portmapper manages RPC connections, which are used by \
#              protocols such as NFS and NIS. The portmap server must be \
#              running on machines which act as servers for protocols which \
#              make use of the RPC mechanism.
# processname: portmap

NAME="yabibe"
TWISTD="/usr/local/stackless/bin/twistd"
BACKEND_DIR="/usr/local/yabi/backend"
TAP="server.py"
RUNDIR="/var/run/yabi/backend"
PIDFILE="${RUNDIR}/${NAME}.pid"

# This is an interactive program, we need the current locale
[ -f /etc/profile.d/lang.sh ] && . /etc/profile.d/lang.sh
# We can't Japanese on normal console at boot time, so force LANG=C.
if [ "$LANG" = "ja" -o "$LANG" = "ja_JP.eucJP" ]; then
    if [ "$TERM" = "linux" ] ; then
        LANG=C
    fi
fi

# Source function library.
. /etc/init.d/functions

#  check for required files
if [ ! -x "${TWISTD}"]
then
        echo "$0: Aborting, no $TWISTD found."
        exit 0
fi
if [ ! -r "${TAP}" ]
then
        echo "$0: Aborting, no file $TAP found."
        exit 0
fi

#  set up run directory if necessary
if [ ! -d "${RUNDIR}" ]
then
        echo "$0: Aborting, running directory $RUNDIR does not exist."
        exit 0
fi

case "$1" in
        start)
                echo -n "Starting $NAME"
                daemon ${TWISTD}  \\
                                --pidfile=$PIDFILE \\
                                --rundir=$RUNDIR \\
                                --logfile=$LOGFILE \\
                                ${TAP}
                status $NAME
                ;;

        stop)
                echo -n "Stopping ${NAME}"
                kill `cat "${PIDFILE}"`
                status $NAME
                ;;

        restart)
                "${0}" stop
                "${0}" start
                ;;

    *)
                echo "Usage: ${0} {start|stop|restart|}" >&2
                exit 1
                ;;
esac

exit 0