import setuptools
import os
from setuptools import setup, find_packages

setup(name='yabibe',
    version='0.2',
    description='Yabi Backend',
    long_description='Yabi back end service',
    author='Centre for Comparative Genomics',
    author_email='web@ccg.murdoch.edu.au',
    packages=['yabibe',
              'yabibe.conf',
              'yabibe.connectors',
              'yabibe.connectors.ex',
              'yabibe.connectors.fs',
              'yabibe.log',
              'yabibe.reactor',
              'yabibe.server',
              'yabibe.server.resources',
              'yabibe.server.resources.ex',
              'yabibe.server.resources.fs',
              'yabibe.server.resources.TaskManager',
              'yabibe.utils',
              'yabibe.utils.pexpect',
              'yabibe.utils.protocol',
              'yabibe.utils.protocol.globus',
              'yabibe.utils.protocol.s3',
              'yabibe.utils.protocol.ssh'
              ],
    package_data={'yabibe': ['conf/*.conf']},
    zip_safe=False,
    scripts=['scripts/yabibe'],
    install_requires=[
        'pyOpenSSL==0.13',
        'pycrypto==2.3',
        'paramiko==1.7.7.1-fifopatch2',
        'Mako==0.7.3',
        'MarkupSafe==0.15',
        'TwistedWeb2==1.0.0',
        'setproctitle==1.1.2',
        'wsgiref==0.1.2',
        'zope.interface==4.0.5',
        'gevent==0.13.8',
        'greenlet==0.4.0',
        'psutil==0.6.1',
        'boto==2.3.0',
        'grequests==0.2.0',
        'requests>=1.0.0',
        'conditional==1.0',
        'twisted==12.0.0',
        'unittest2',
        'coverage',
        'mock',
        'nose',
        'pyaml',
    ],
    dependency_links = [
          "http://repo.ccgapps.com.au",
          "http://yabi.googlecode.com/files/paramiko-1.7.7.1-fifopatch2.tar.gz",
          "https://twisted-web2.googlecode.com/files/TwistedWeb2-1.0.0.tar.gz?"    # see: http://stackoverflow.com/questions/2653410/project-hosting-on-google-code-files-are-cached
    ],      
)
