# 
FROM muccg/python-base:ubuntu14.04-2.7
MAINTAINER https://github.com/muccg/yabi/

ARG GIT_TAG=next_release
ARG PIP_OPTS="--no-cache-dir"

ENV GITTAG $GIT_TAG

ENV DEBIAN_FRONTEND noninteractive

# Project specific deps
RUN apt-get update && apt-get install -y --no-install-recommends \
  git \
  libpcre3 \
  libpcre3-dev \
  libpq-dev \
  libssl-dev \
  libxml2-dev \
  libxslt1-dev \
  krb5-config \
  krb5-user \
  libkrb5-dev \
  libssl-dev \
  libsasl2-dev \
  libldap2-dev \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN env --unset=DEBIAN_FRONTEND

WORKDIR /app
COPY .version /.version
RUN echo $GIT_TAG \
    && git clone --depth=1 --branch=$GITTAG https://github.com/muccg/yabi.git .

# install python deps
RUN virtualenv /env
RUN /env/bin/pip ${PIP_OPTS} install -r yabish/runtime-requirements.txt
RUN /env/bin/pip ${PIP_OPTS} install -e yabish
RUN /env/bin/pip ${PIP_OPTS} install -r yabi/runtime-requirements.txt
RUN /env/bin/pip ${PIP_OPTS} install -e yabi

EXPOSE 9100 9101
VOLUME ["/data"]

RUN chmod +x /app/docker-entrypoint.sh

# Drop privileges, set home for ccg-user
USER ccg-user
ENV HOME /data
WORKDIR /data

ENTRYPOINT ["/app/docker-entrypoint.sh"]
CMD ["uwsgi"]
