#!/usr/bin/env python
#
# twistd with server.py
#

### Twisted Preamble
# This makes sure that users don't have to set up their environment
# specially in order to run these programs from bin/.
import sys, os, string
if string.find(os.path.abspath(sys.argv[0]), os.sep+'Twisted') != -1:
    sys.path.insert(0, os.path.normpath(os.path.join(os.path.abspath(sys.argv[0]), os.pardir, os.pardir)))
if hasattr(os, "getuid") and os.getuid() != 0:
    sys.path.insert(0, os.path.abspath(os.getcwd()))
### end of preamble

# before we run the server, we want to find the python server.py
import yabibe.server
serverfile = yabibe.server.__file__

if serverfile.endswith(".pyc"):
    serverfile = serverfile[:-4]+".py"

# python we're in
python = os.path.realpath(sys.executable)

# our twistd will be along side the python executable
pythonbase = os.path.dirname(python)
twistd = "%s/twistd"%(pythonbase)

# now lets run our server

command = [python,twistd,"-y",serverfile]+sys.argv[1:]
os.execv(command[0], command)
