#!/bin/bash
# Default params, override in /etc/sysconfig/celeryd
SOURCE="/usr/local/python/ccgapps/yabiadmin/release/yabiadmin"
LOG="$SOURCE/logs/celeryd.log"
VIRTUAL_PYTHON="$SOURCE/virtualpython"
CELERYD="$VIRTUAL_PYTHON/bin/celeryd"
USER=apache

# required by celeryd
DJANGO_SETTINGS_MODULE="settings"
DJANGO_PROJECT_DIR="$SOURCE"
CELERY_LOADER="django"
CELERY_CHDIR="$SOURCE"
PYTHONPATH="/usr/local/etc/ccgapps:$SOURCE:/usr/local/python/ccgapps/yabiadmin/release"
PYTHON_EGG_CACHE="/usr/local/python/ccgapps/yabiadmin/.egg_cache"
PROJECT_DIRECTORY="$SOURCE"
export DJANGO_SETTINGS_MODULE DJANGO_PROJECT_DIR CELERY_LOADER CELERY_CHDIR PYTHONPATH PROJECT_DIRECTORY PYTHON_EGG_CACHE

$VIRTUAL_PYTHON/bin/celeryd &> ${LOG} &
