begin;
alter table   yabmin_backend rename to yabi_backend;
alter table   yabmin_backendcredential rename to yabi_backendcredential;
alter table   yabmin_credential rename to yabi_credential;
alter table   yabmin_fileextension rename to yabi_fileextension;
alter table   yabmin_filetype rename to yabi_filetype;
alter table   yabmin_filetype_extensions rename to yabi_filetype_extensions;
alter table   yabmin_parameterfilter rename to yabi_parameterfilter;
alter table   yabmin_parameterswitchuse rename to yabi_parameterswitchuse;
alter table   yabmin_tool rename to yabi_tool;
alter table   yabmin_toolgroup rename to yabi_toolgroup;
alter table   yabmin_toolgrouping rename to yabi_toolgrouping;
alter table   yabmin_tooloutputextension rename to yabi_tooloutputextension;
alter table   yabmin_toolparameter rename to yabi_toolparameter;
alter table   yabmin_toolparameter_accepted_filetypes rename to yabi_toolparameter_accepted_filetypes;
alter table   yabmin_toolparameter_input_extensions rename to yabi_toolparameter_input_extensions;
alter table   yabmin_toolset rename to yabi_toolset;
alter table   yabmin_user rename to yabi_user;
alter table   yabmin_user_toolsets rename to yabi_user_toolsets;
commit;
