#!/usr/bin/perl
# TEST: ./bin/yabiLinks schibeci default NCBI.nt.json,NCBI.aa.json,kegg.nt.json,kegg_cog.aa.json

    use strict;

    # CONSTANT
    my $yabi_root = '/yabi';
    my $yabi_tools = $yabi_root . '/yabi-tools';
    my $yabi_json = $yabi_root . '/yabi-json';
    my $yabi_jobs = $yabi_root . '/yabi-jobs';

    # INPUT
    my $user = $ARGV[0];
    my $tools = $ARGV[1];
    my $blast = $ARGV[2];

    # LOCAL
    my $json; # json in questtion
    my $tool; # tool in question
    my @tmp;  # temporary array


    if ($user eq '') {
    	print "Must define user\n";
        exit(1);
    }

    # tools
    @tmp = split /,/, $tools;
    foreach $tool (@tmp) {
        if (-l "$yabi_jobs/$user/.tools/$tool") {
            print "Removing $tool from $yabi_jobs/$user/.tools/\n";
            system "cd $yabi_jobs/$user/.tools/ ; rm -f $tool";
        }
        print "Creating link to $yabi_tools/$tool in $yabi_jobs/$user/.tools/\n";
        system "cd $yabi_jobs/$user/.tools/ ; ln -s $yabi_tools/$tool $tool";
    }

    # blast
    @tmp = split /,/, $blast;

    if (-d "$yabi_jobs/$user/.blast/") {
    } else {
       # directory does not exist
       print "Creating $yabi_jobs/$user/.blast/\n";
       system "mkdir $yabi_jobs/$user/.blast/ ; chmod 700 $yabi_jobs/$user/.blast/";
    }

    foreach $json (@tmp) {
        if (-l "$yabi_jobs/$user/.blast/$json") {
            print "Removing $json from $yabi_jobs/$user/.blast/\n";
            system "cd $yabi_jobs/$user/.blast/ ; rm -f $json";
        }
        print "Creating link to $yabi_json/$json in $yabi_jobs/$user/.blast/\n";
        system "cd $yabi_jobs/$user/.blast/ ; ln -s $yabi_tools/$json $json";
    }
