#!/usr/bin/python

#
# twistd with server.py
#

### Twisted Preamble
# This makes sure that users don't have to set up their environment
# specially in order to run these programs from bin/.
import sys, os, string
if string.find(os.path.abspath(sys.argv[0]), os.sep+'Twisted') != -1:
    sys.path.insert(0, os.path.normpath(os.path.join(os.path.abspath(sys.argv[0]), os.pardir, os.pardir)))
if hasattr(os, "getuid") and os.getuid() != 0:
    sys.path.insert(0, os.path.abspath(os.getcwd()))
### end of preamble

# before we run the server, we want to find the python server.py
import yabibe.server
serverfile = yabibe.server.__file__

# now add this to out sys.argv
sys.argv.append('--python=%s'%serverfile)

from twisted.scripts.twistd import run
run()

