export YABISTORE="localhost:9003/yabistore"
export YABIBACKEND="localhost:9001/"
export DJANGO_SETTINGS_MODULE="settings"
export CUSTOMDB="1"
export HTTP_REDIRECT_TO_HTTPS="faramir.localdomain:9432"
export ADMIN_EMAIL_NAME="Crispin Wellington"
export ADMIN_EMAIL="cwellington@ccg.murdoch.edu.au"
export DATABASE_ENGINE="postgresql_psycopg2"
export DATABASE_NAME="dev_yabi"
export DATABASE_USER="yabminapp"
export DATABASE_PASSWORD="yabminapp"
export DATABASE_HOST="eowyn.localdomain"
export DATABASE_PORT="5432"
export AUTH_LDAP_SERVER="ldaps://fds1.localdomain ldaps://fds2.localdomain ldaps://fds3.localdomain"
export AUTH_LDAP_USER_BASE="ou=People,dc=ccg,dc=murdoch,dc=edu,dc=au"
export AUTH_LDAP_GROUP_BASE="ou=Yabi,ou=Web Groups,dc=ccg,dc=murdoch,dc=edu,dc=au"
export AUTH_LDAP_GROUP="yabi"
export AUTH_LDAP_DEFAULT_GROUP="baseuser"

